INSERT INTO public.item ("name","icon","desc") VALUES ('GELEIA OCEÂNICA','ingredients/9.png','Uma geleia que possui um gosto azedo bem interessante. É muito usado em poções que relacionadas ao corpo.');
INSERT INTO public.item ("name","icon","desc") VALUES ('ESCARAVELHO AMARELADO','ingredients/14.png','Mesmo parecendo um escaravelho, esse estranho doce é feito de um açúcar mágico! É ótimo para gerar itens que mexam com os sentimentos!');
INSERT INTO public.item ("name","icon","desc") VALUES ('FRUTA RAINHA','ingredients/3.png','Essa fruta é apimentada, mas também um pouco refrescante! Ótima para criar itens que possuam efeitos diversos!');
INSERT INTO public.item ("name","icon","desc") VALUES ('ESCARAVELHO GELATINOSO','ingredients/15.png','Essa incrível gelatina da uma sensação de nostalgia em que a consome!');
INSERT INTO public.item ("name","icon","desc") VALUES ('SOPA DA VELOCIDADE','ingredients/8.png','Essa sopa faz com que você se lembre como era brincar de pega-pega quando criança, e com isso aumenta sua velocidade!');
INSERT INTO public.item ("name","icon","desc") VALUES ('GALHO QUENTE','ingredients/4.png','Esse galho emite calor e quando quebrado ele pega fogo! Ótimo para acender uma churrasqueira!');
INSERT INTO public.item ("name","icon","desc") VALUES ('FRUTO ROXO','ingredients/1.png','Esse fruto gelatinoso da uma sensação refrescante no corpo de quem o come! É muito usado para combater febres!');
INSERT INTO public.item ("name","icon","desc") VALUES ('CRANIO MARSHMALLOW','ingredients/6.png','Esse cranio é tão fofo que traz boas sensações aquele que o come!');
INSERT INTO public.item ("name","icon","desc") VALUES ('CARVÃO MISTERIOSO','ingredients/7.png','Esse carvão é difícil de ser acendido, entretanto, após pegar fogo ele é difícil de apagar.');
INSERT INTO public.item ("name","icon","desc") VALUES ('OVO DE GELATINA','ingredients/5.png','Esse ovo é tão gostoso que dá até uma animação em quem o come.');
INSERT INTO public.item ("name","icon","desc") VALUES ('JOANINHA DE CHOCOLATE','ingredients/2.png','Essa joaninha de chocolate faz com que quem a coma se coloque no lugar dos outros!');
INSERT INTO public.item ("name","icon","desc") VALUES ('AÇÚCAR ANIMADO','ingredients/20.png','Esse açúcar da a energia necessária para concluir suas tarefas! Mas cuidado! Muito açúcar faz mal!');
INSERT INTO public.item ("name","icon","desc") VALUES ('SUCO DA ANIMAÇÃO','ingredients/13.png','Esse suco dá mais energia para que o toma! Crianças que o tomam não dormem de tanta energia!');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO DA CURA','potions/1.png','Essa poção é ótima para combater gripes e resfriados! Nunca deixe faltar em casa!');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO DO CALOR','potions/2.png','Perfeita para os dias frios e para esquentar rapidamente o jantar! Tem um gostinho de mel com limão!');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO DA AMIZADE','potions/3.png','Fazer amigos pode ser complicado, essa poção te da a confiança de tentar fazer novas amizades!');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO DA ANIMAÇÃO','potions/6.png','A animação é necessária para chegar cada vez mais longe! Essa poção pode te ajudar a manter a animação!');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO GELADA','potions/8.png','Essa poção é capaz de congelar quase qualquer coisa! Use com cuidado!');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO DA FOME','potions/12.png','Essa poção mata a fome de qualquer um, mas só a use quando  necessário, afinal, comer é muito bom!!');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO DOS SONHOS','potions/20.png','Tome essa poção antes de dormir para sonhar com o que você desejar!');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO PERIGOSA','potions/17.png','Essa poção é um medicamento poderoso, só tome sob recomendação médica!');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO RETRÔ','potions/21.png','Você se sente nos anos 80.');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO DA PROGRAMAÇÃO','potions/7.png','“Sem animação não há programação” – Kenji, o arquimago');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO DO AMOR','potions/19.png','Um presente muito bom para dar para pessoas amadas. Ela não tem nenhum efeito, mas foi feita com amor!');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO DA DETERMINAÇÃO','potions/16.png','Ter misturados os ingredientes corretos para criar essa poção de enche de Determinação!');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO DO CHURRASCO','potions/14.png','Dizem que um famoso mago ainda deve uma dessas poções para uma turma de aprendizes…');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO FILOSOFAL','potions/4.png','Uma poção que cura praticamente todas as doenças, mas muito difícil de ser feita.');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO DO VERÃO','potions/5.png','Transforma qualquer dia em um lindo dia de verão!');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO DO INVERNO','potions/9.png','Ótima para quando você quiser ficar embaixo das cobertas, com pipoca e um bom filme!');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO DO ESTUDO','potions/10.png','Te ajuda a se concentrar naquele momento antes de uma prova!');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO DOS ANIMAIS','potions/11.png','Deixa que você fale com os animais por um tempinho! Seu pet deve ter muito pra te contar!');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO DA EMPATIA','potions/13.png','As pessoas boas devem amar seus inimigos. - Seu madruga');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO MISTERIOSA','potions/15.png','Ninguém sabe o que essa poção faz, mas ela tem gosto de limonada!');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO DA CORAGEM','potions/18.png','A coragem não consiste em não sentir medo, mas em superar o medo.  - Chesperito');
INSERT INTO public.item ("name","icon","desc") VALUES ('POÇÃO BUGADA','potions/22.png','Algo de errado não está certo…');
INSERT INTO public.item ("name","icon","desc") VALUES ('ALPHA EDTECH','eastereggs/alpha.png','Uma comunidade do bem, onde todos estão dispostos a ajudar!');
INSERT INTO public.item ("name","icon","desc") VALUES ('MAGO ALEHF','eastereggs/dev_alehf.png','Um mago que está trabalhando em um projeto de um jogo...');
INSERT INTO public.item ("name","icon","desc") VALUES ('MAGO BRUNO','eastereggs/dev_Bruno.png','Um mago especializado em deixar as coisas bonitas!');
INSERT INTO public.item ("name","icon","desc") VALUES ('MAGO JOÃO','eastereggs/Dev_João.png','Um mago que manja da construção de feitiços, e também de programação!');
INSERT INTO public.item ("name","icon","desc") VALUES ('MAGO LUÍS','eastereggs/dev_Luiz.png','Um mago que comanda um grupo de magos na criação de um jogo sobre alquimia! Que loucura.');
INSERT INTO public.item ("name","icon","desc") VALUES ('MAGO PLINIO','eastereggs/dev_plinio.png','Um mago especializado em contar histórias! É parte de um grupo que está trabalhando em um projeto secreto…');
INSERT INTO public.item ("name","icon","desc") VALUES ('KENJI, O ARQUIMAGO','eastereggs/Img_Kenji.png','O arquimago da escola de magia “Alpha Edtech”, preza a animação de seus estudantes!');
INSERT INTO public.item ("name","icon","desc") VALUES ('SAMIR, O MAGO','eastereggs/samir.png','Samir é a conexão entre a escola de magia e seus estudantes! Diz a lenda que ele deve um churrasco a duas turmas diferentes!');
INSERT INTO public.item ("name","icon","desc") VALUES ('BUG','eastereggs/kenji_bug.png','Algo deu errado e outro bug apareceu! O arquimago vai puxar a sua orelha!');
